### ISSUE TITLE
Database Exception

### ISSUE THREAD

**Issue by Lennso** [dutchheight/craft-cookie-boss#15]
<img width="1018" alt="Bildschirmfoto 2020-09-08 um 10 48 20" src="https://user-images.githubusercontent.com/11076634/92454876-4a8da380-f1c1-11ea-89e6-2db04d824ad7.png">

I got this database exception in Front- and Backend (Settings) after the last update...

Thanks

**Comment by KevinBeckers** [comment]
Fixed in v1.3.2

**Comment by Lennso** [comment]
Sorry, but the plugin isnt working at all. i cant install it anymore.

<img width="328" alt="Bildschirmfoto 2020-09-10 um 10 26 18" src="https://user-images.githubusercontent.com/11076634/92701295-1694b880-f350-11ea-85c7-96a17ab4e46b.png">

**Comment by KevinBeckers** [comment]
What is the current state of the plugin? Can you post you log? I am not able to recreate this error.

**Comment by Lennso** [comment]
I uninstalled the plugin and installed it back again with composer with no errors. then i tried to install the plugin in backend but it didnt work

[web.log](https://github.com/dutchheight/craft-cookie-boss/files/5200300/web.log)

**Comment by KevinBeckers** [comment]
Can you install v1.3.2.2 and see if this version works?

**Comment by Lennso** [comment]
Thanks. Its working now!

**Comment by KevinBeckers** [comment]
Good! Thank you for using Cookie Boss. Feel free to contact if you encounter other problems.
