### ISSUE TITLE
Vue Version problem

### ISSUE THREAD

**Issue by codanator** [dutchheight/craft-cookie-boss#18]
Hy,

In askConsent/_index.twig you are importing vue without a specific version.
Since vue3 is now default and your components are not vue3 ready it gives an error.

Fixed it with:

<script src="https://cdn.jsdelivr.net/npm/vue@2.6.12"></script>

in _index.twig

**Comment by KevinBeckers** [comment]
Thx, will try to fix asap.

**Comment by KevinBeckers** [comment]
Fixed in next release.
