### ISSUE TITLE
Their is misspelled "there" in a couple place

### ISSUE THREAD

**Issue by jdsimcoe** [dutchheight/craft-cookie-boss#3]
![image](https://user-images.githubusercontent.com/275617/67589705-eb8c8080-f70d-11e9-94eb-073b78275b01.png)
In this screenshot, there should be "their" since it refers back to a person.

Also there are two more highlighted places where "there" should be there on the main repo description and in `README.md`:

![image](https://user-images.githubusercontent.com/275617/67589773-1c6cb580-f70e-11e9-9ae4-6292dc108cbb.png)

**Comment by JayBox325** [comment]
This is still appearing for me on the plugin store.

**Comment by KevinBeckers** [comment]
I changed it in craftid. Don't know the update cycle.

**Comment by JayBox325** [comment]
Ok, perfect. No worries, just thought I'd flag incase.

**Comment by KevinBeckers** [comment]
Thanks!
