### ISSUE TITLE
Not working with forced trailing slashes in url

### ISSUE THREAD

**Issue by WHITE-developer** [dutchheight/craft-cookie-boss#4]
Accepting the modal isn't working on a setup that requires trailing slashes in the url.

We rewrite all non trailing slashes to trailing, so had to add an exception for the `/cookie-boss/save-consent-settings`. Would be nicer to use the `action` in the form submit directly.

**Comment by KevinBeckers** [comment]
Thanks for the suggestion. I will implement this in the next release.

**Comment by KevinBeckers** [comment]
I will release v1.1.2 today in which I implemented 'addTrailingSlashesToUrls' from the Craft config.
So `'addTrailingSlashesToUrls' => true` will result in trailing slashes in all plugin form's.

**Comment by WHITE-developer** [comment]
One small comment on this, getting an deprecation warning now :smile: 
https://github.com/dutchheight/craft-cookie-boss/commit/2a0f17a6af3d1b6c64365eb6c0e53700b3ab2af6#diff-0c14f21b3835d002e50d158232c6110eR19
`craft.config.[setting] has been deprecated. Use craft.app.config.general.setting instead.`

**Comment by KevinBeckers** [comment]
Fixed in v1.1.3
