### ISSUE TITLE
Settings message not saving

### ISSUE THREAD

**Issue by WHITE-developer** [dutchheight/craft-cookie-boss#5]
Hi again :)

I found out the `messageSettings` is missing in the `SettingsController.php` so it doesn't save.
Adding `$settings['messageSettings'] = Craft::$app->getRequest()->getRequiredBodyParam('messageSettings');` solves the issue.

**Comment by KevinBeckers** [comment]
Hi, which version do you use?
This should be fixed in 751d63e8ff126accdde06f4df78279203c676a14

**Comment by WHITE-developer** [comment]
Latest tagged version 1.1.0, that's the issue then, 1.1.1 isn't in composer :smile:

**Comment by KevinBeckers** [comment]
I noticed it, sorry. V1.1.1 is released.
