### ISSUE TITLE
FR: changable cookie name

### ISSUE THREAD

**Issue by WHITE-developer** [dutchheight/craft-cookie-boss#7]
I need to refresh the cookie consent cause we added a new group to it. Only way to do this, where I could think about, is to change the cookie-boss cookie so everyone that accepted it has to re-accept.

Could there be a setting created to change the cookie name? Or any other idea?

**Comment by KevinBeckers** [comment]
A good idea will implement this in the next version!

**Comment by KevinBeckers** [comment]
I added consent invalidation in v1.2.0. Choose "Save and invalidate consent" in the settings. Please let me know if this is what you needed.
